apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: adservice
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/mrbakach/app-microservices-demo
    targetRevision: 1.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true